using System;
using System.Collections.Generic;

namespace EDT {

    public enum CharacterTypes {
        None,
        Class_Melee,
        Class_Ranged,
        Class_Mage,
    }

    public enum CharacterUnlockState {
        None,
        Free,
        Currency,
    }

    public enum CharacterGrade {
        None,
        Star_01,
        Star_02,
        Star_03,
        Star_04,
        Star_05,
    }

    public enum ConsumableType {
        None,
        Potion,
        Scroll,
        ItemBox,
    }

    public enum EquipmentTypes {
        None,
        Weapon,
        Armor,
        Accessory,
    }

    public enum ItemGradeTypes {
        None,
        Normal,
        Magic,
        Rare,
        Epic,
        Legendary,
    }

    public enum GachaTypes {
        None,
        Equipment,
        Skill,
    }

    public enum BattleType {
        None,
        Wave,
        Raid,
    }

    public enum MaterialType {
        None,
        Enchant,
        Craft,
    }

    public enum MonsterTypes {
        None,
        Normal,
        Elite,
        Boss,
    }

    public enum RewardTypes {
        None,
        Material,
        Equipment,
        Experience,
        Gold,
    }

    public enum SkillCastingTypes {
        None,
        Instant,
        OnHitCaster,
        OnHitTarget,
        Passive,
        Casting,
    }

    public enum SkillApplyTarget {
        None,
        Self,
        Enemy,
        Friendly,
        All,
    }

    public enum SkillScanType {
        None,
        Target,
        Circle,
        Sector,
        Line,
        Donut,
    }

    public enum SkillDamageType {
        None,
        Physical,
        Magical,
        Pure,
    }

    public enum SkillEffectTypes {
        None,
        Damage,
        ActivateBuff,
        DeactivateBuff,
        IncreaseAttribute,
        DecreaseAttribute,
        SpawnProjectile,
        ActivateAura,
    }

    public enum SkillAnchorType {
        None,
        Root,
        Center,
    }

    public enum SkillCardGrade {
        None,
        Normal,
        Magic,
        Rare,
        Epic,
        Legendary,
    }

    public enum UIZOrder {
        None,
        Background,
        Hud,
        View,
        Popup,
        Tooltip,
        Feedback,
        Notice,
        Loading,
        Fade,
        Interaction,
        DevConsole,
    }

    public enum UIEventIDs {
        None,
        Confirm,
        Cancel,
        Close,
        Select,
        Btn1,
        Btn2,
        Btn3,
        Btn4,
    }

    public enum CurrencyInfo {
        None,
        Gold,
        Dia,
        GoldDungeonTicket,
        ExpDungeonTicket,
        RaidTicket,
        PVPTicket,
    }

    public enum SkillInfo {
        None,
        SKILL_BASEATTACK_01,
        SKILL_BASEATTACK_02,
        SKILL_BASEATTACK_03,
        SKILL_POWERATTACK_01,
        SKILL_POWERATTACK_02,
        SKILL_POWERATTACK_03,
        SKILL_SPECIALATTACK_01,
        SKILL_SPECIALATTACK_02,
        SKILL_SPECIALATTACK_03,
        SKILL_PASSIVE_01,
        SKILL_PASSIVE_02,
        SKILL_MONSTER_ATK_MELEE_01,
        SKILL_MONSTER_ATK_RANGE_01,
        SKILL_MONSTER_MATK_RANGE_01,
        SKILL_BREAK,
        SKILL_CLASS_BASIC_01,
        SKILL_CLASS_BASIC_02,
        SKILL_DASH_01,
        SKILL_DASH_ATTACK_01,
        SKILL_CASTING_ATTACK_01,
        SKILL_CASTING_ATTACK_02,
        SKILL_CASTING_ATTACK_03,
        SKILL_DAMAGE_IMMUNITY,
        SKILL_PROJECTILE_ATTACK_01,
        SKILL_PROJECTILE_ATTACK_02,
        SKILL_PROJECTILE_ATTACK_03,
        SKILL_HERO_01_SLOT1_LV1,
        SKILL_HERO_01_SLOT1_LV2,
        SKILL_HERO_01_SLOT1_LV3,
        SKILL_HERO_01_SLOT1_LV4,
        SKILL_HERO_01_SLOT1_LV5,
        SKILL_HERO_01_SLOT2_LV1,
        SKILL_HERO_01_SLOT2_LV2,
        SKILL_HERO_01_SLOT2_LV3,
        SKILL_HERO_01_SLOT2_LV4,
        SKILL_HERO_01_SLOT2_LV5,
        SKILL_HERO_01_SLOT3_LV1,
        SKILL_HERO_01_SLOT3_LV2,
        SKILL_HERO_01_SLOT3_LV3,
        SKILL_HERO_01_SLOT3_LV4,
        SKILL_HERO_01_SLOT3_LV5,
        SKILL_HERO_01_SLOT4_LV1,
        SKILL_HERO_01_SLOT4_LV2,
        SKILL_HERO_01_SLOT4_LV3,
        SKILL_HERO_01_SLOT4_LV4,
        SKILL_HERO_01_SLOT4_LV5,
        SKILL_HERO_01_SLOT5_LV1,
        SKILL_HERO_01_SLOT5_LV2,
        SKILL_HERO_01_SLOT5_LV3,
        SKILL_HERO_01_SLOT5_LV4,
        SKILL_HERO_01_SLOT5_LV5,
    }

    public enum SkillEffect {
        None,
        SE_TAKE_DAMAGE_01,
        SE_TAKE_DAMAGE_02,
        SE_TAKE_DAMAGE_03,
        SE_TAKE_DAMAGE_04,
        SE_TAKE_DAMAGE_05,
        SE_MONSTER_PHYSICAL_DAMAGE_01,
        SE_MONSTER_MAGICAL_DAMAGE_01,
        SE_TAKE_DAMAGE_06,
        SE_TAKE_DAMAGE_07,
        SE_TAKE_DAMAGE_08,
        SE_ACTIVATE_BUFF_MOVESPEED_01,
        SE_INCREASE_MOVESPEED_01,
        SE_ACTIVATE_BUFF_ATTACKSPEED_01,
        SE_INCREASE_ATTACKSPEED_01,
        SE_ACTIVATE_DEBUFF_MOVESPEED_01,
        SE_DECREASE_MOVESPEED_01,
        SE_TAKE_DAMAGE_101,
        SE_ACTIVATE_DEBUFF_BREAK_01,
        SE_ACTIVATE_DEBUFF_BREAK_02,
        SE_DECREASE_DAMAGETAKEN,
        SE_DASH_ATTACK_DAMAGE_01,
        SE_CASTING_DAMAGE_01,
        SE_CASTING_DAMAGE_02,
        SE_CASTING_DAMAGE_03,
        SE_ACTIVATE_BUFF_DAMAGE_IMMUNITY,
        SE_SPAWNPOJECTILE_01,
        SE_SPAWNPOJECTILE_02,
        SE_SPAWNPOJECTILE_03,
        SE_PROJECTILE_DAMAGE_01,
        SE_HERO_01_SLOT1_DAMAGE_01,
        SE_HERO_01_SLOT1_DAMAGE_02,
        SE_HERO_01_SLOT1_DAMAGE_03,
        SE_HERO_01_SLOT1_DAMAGE_04,
        SE_HERO_01_SLOT1_DAMAGE_05,
        SE_HERO_01_SLOT2_DAMAGE_01,
        SE_HERO_01_SLOT2_DAMAGE_02,
        SE_HERO_01_SLOT2_DAMAGE_03,
        SE_HERO_01_SLOT2_DAMAGE_04,
        SE_HERO_01_SLOT2_DAMAGE_05,
        SE_HERO_01_SLOT3_INCREASE_MOVESPEED_01,
        SE_HERO_01_SLOT3_INCREASE_MOVESPEED_02,
        SE_HERO_01_SLOT3_INCREASE_MOVESPEED_03,
        SE_HERO_01_SLOT3_INCREASE_MOVESPEED_04,
        SE_HERO_01_SLOT3_INCREASE_MOVESPEED_05,
        SE_HERO_01_SLOT3_INCREASE_ATTACKSPEED_01,
        SE_HERO_01_SLOT3_INCREASE_ATTACKSPEED_02,
        SE_HERO_01_SLOT3_INCREASE_ATTACKSPEED_03,
        SE_HERO_01_SLOT3_INCREASE_ATTACKSPEED_04,
        SE_HERO_01_SLOT3_INCREASE_ATTACKSPEED_05,
        SE_HERO_01_SLOT4_ACTIVATE_BUFF_ATTACKRATIO_01,
        SE_HERO_01_SLOT4_ACTIVATE_BUFF_ATTACKRATIO_02,
        SE_HERO_01_SLOT4_ACTIVATE_BUFF_ATTACKRATIO_03,
        SE_HERO_01_SLOT4_ACTIVATE_BUFF_ATTACKRATIO_04,
        SE_HERO_01_SLOT4_ACTIVATE_BUFF_ATTACKRATIO_05,
        SE_HERO_01_SLOT4_INCREASE_ATTACKRATIO_01,
        SE_HERO_01_SLOT4_INCREASE_ATTACKRATIO_02,
        SE_HERO_01_SLOT4_INCREASE_ATTACKRATIO_03,
        SE_HERO_01_SLOT4_INCREASE_ATTACKRATIO_04,
        SE_HERO_01_SLOT4_INCREASE_ATTACKRATIO_05,
        SE_HERO_01_SLOT4_AURA_01,
        SE_HERO_01_SLOT4_AURA_02,
        SE_HERO_01_SLOT4_AURA_03,
        SE_HERO_01_SLOT4_AURA_04,
        SE_HERO_01_SLOT4_AURA_05,
        SE_HERO_01_SLOT5_DAMAGE_01,
        SE_HERO_01_SLOT5_DAMAGE_02,
        SE_HERO_01_SLOT5_DAMAGE_03,
        SE_HERO_01_SLOT5_DAMAGE_04,
        SE_HERO_01_SLOT5_DAMAGE_05,
    }

    public enum BuffInfo {
        None,
        BUFF_MOVESPEED_01,
        BUFF_ATTACKSPEED_01,
        DEBUFF_MOVESPEED_01,
        DEBUFF_STUN,
        DEBUFF_SILENCE,
        DEBUFF_BINDING,
        DEBUFF_BREAK,
        BUFF_DAMAGE_IMMUNITY,
        BUFF_HERO_01_SLOT4_ATTACKRATIO_01,
        BUFF_HERO_01_SLOT4_ATTACKRATIO_02,
        BUFF_HERO_01_SLOT4_ATTACKRATIO_03,
        BUFF_HERO_01_SLOT4_ATTACKRATIO_04,
        BUFF_HERO_01_SLOT4_ATTACKRATIO_05,
    }

    public enum StatInfo {
        None,
        ATK,
        ATK_Base,
        ATK_Add,
        ATK_Ratio,
        ATK_Amp,
        Pen_Physical,
        MATK,
        MATK_Base,
        MATK_Add,
        MATK_Ratio,
        MATK_Amp,
        Pen_Magic,
        CritRate,
        CritRate_Base,
        CritRate_Add,
        CritDam,
        CritDam_Base,
        CritDam_Add,
        SuperCritRate,
        SuperCritRate_Base,
        SuperCritRate_Add,
        SuperCritDam,
        SuperCritDam_Base,
        SuperCritDam_Add,
        MaxHP,
        MaxHP_Base,
        MaxHP_Add,
        MaxHP_Ratio,
        MaxHP_Amp,
        DEF,
        DEF_Base,
        DEF_Add,
        DEF_Ratio,
        MDEF,
        MDEF_Base,
        MDEF_Add,
        MDEF_Ratio,
        HpRecovery,
        HpRecovery_Base,
        HpRecovery_Add,
        HpRecovery_Ratio,
        LifeSteal_Ratio,
        SpellVamp_Ratio,
        DamageReduction,
        DamageReduction_Base,
        DamageReduction_Add,
        DamageTakenAmp,
        DamageTakenAmp_Base,
        DamageTakenAmp_Add,
        AtkSpeed,
        AtkSpeed_Base,
        AtkSpeed_Add,
        AtkSpeed_Ratio,
        MoveSpeed,
        MoveSpeed_Base,
        MoveSpeed_Add,
        MoveSpeed_Ratio,
        BreakGage,
        BreakGage_Base,
        BreakGage_Add,
        BreakGage_Ratio,
        BreakGage_Amp,
        BreakDamage,
        BreakDamage_Base,
        BreakDamage_Add,
        BreakDamage_Ratio,
        BreakDamage_Amp,
        BreakRecovery,
        BreakRecovery_Base,
        BreakRecovery_Add,
        BreakRecovery_Ratio,
        BreakRecovery_Amp,
        KnockBack,
        KnockBack_Base,
        KnockBack_Add,
        KnockBack_Ratio,
        KnockBackResist,
        KnockBackResist_Base,
        KnockBackResist_Add,
        KnockBackResist_Ratio,
        MaxStamina,
        MaxStamina_Base,
        MaxStamina_Add,
        MaxStamina_Ratio,
        MaxStamina_Amp,
        StaminaRegen,
        StaminaRegen_Base,
        StaminaRegen_Add,
        StaminaRegen_Ratio,
        StaminaRegen_Amp,
        StaminaSteal,
        StaminaSteal_Base,
        StaminaSteal_Add,
        StaminaSteal_Ratio,
        StaminaSteal_Amp,
        Block,
        Block_Base,
        Block_Add,
        DamBoss_Ratio,
        DamNormal_Ratio,
        GoldBonus_Ratio,
        ExpBonus_Ratio,
        ItemDrop_Ratio,
    }

    public enum UIWidgetPath {
        None,
        IntroBG,
        IntroHUD,
        LegalNotice,
        LoginBG,
        LoginHUD,
        LoginServerList,
        LoginNotice,
        MainHUD,
        PlayerStats,
        SkillSlot,
        WorldMap,
        Inventory,
        ItemTooltip,
        SkillTree,
        SkillTooltip,
        DamageText,
        SystemNotice,
        LoadingScreen,
        FadeEffect,
        DragVisual,
        GameCursor,
        DevConsole,
    }

    public enum TableType {
        None,
        TableCharacter,
        TableLevelExp,
        TableUnlockCondition,
        TableLevelupCost,
        TableCharacterTrait,
        TableConsumable,
        TableCurrencyInfo,
        TableEquipment,
        TableEnchant,
        TableCraft,
        TableGachaInfo,
        TableGacha_Equipment,
        TableMapInfo,
        TableMonsterSpawnInfo,
        TableMaterial,
        TableMonster,
        TableMonsterPhase,
        TableReward,
        TableSkillInfo,
        TableSkillEffect,
        TableBuffInfo,
        TableSkillSet,
        TableSkillCard,
        TableSkillCardUpgrade,
        TableSkinInfo,
        TableStatInfo,
        TableBaseStat,
        TableLevelupStat,
        TableUIWidgetPath,
    }

}
