using System;
using System.Collections.Generic;

namespace EDT {

    public enum CharacterTypes {
        None,
        Class_Basic,
        Class_Knight,
        Class_Berserker,
        Class_RuneBlader,
    }

    public enum ConsumableType {
        None,
        Potion,
        Scroll,
        ItemBox,
    }

    public enum CurrencyType {
        None,
        Gold,
        Dia,
        GoldDungeonTicket,
        ExpDungeonTicket,
        RaidTicket,
        PVPTicket,
    }

    public enum EquipmentType {
        None,
        Weapon,
        Armor,
        Accessory,
        Artifact,
    }

    public enum ItemMainCategory {
        None,
        Currency,
        Equipment,
        Material,
        Consumable,
    }

    public enum ItemSubCategory {
        None,
        Gold,
        Dia,
        DungeonTicket,
        PvpToken,
        EventToken,
        Weapon,
        Armor,
        Accessory,
        Artifact,
        EnhanceStone,
        EvolveStone,
        CraftMaterial,
        Rune,
        Potion,
        Scroll,
        Box,
    }

    public enum ItemRarity {
        None,
        Common,
        Magic,
        Rare,
        Epic,
        Legendary,
        Mythic,
    }

    public enum MapType {
        None,
        Stage,
        Dungeon,
    }

    public enum DungeonType {
        None,
        Gold,
        Exp,
        Raid,
    }

    public enum MaterialType {
        None,
        Enchant,
        Craft,
        Rune,
    }

    public enum MonsterTypes {
        None,
        Normal,
        Elite,
        Boss,
    }

    public enum SkillCastingTypes {
        None,
        Instant,
        OnHit,
        Passive,
        Casting,
    }

    public enum SkillApplyTarget {
        None,
        Self,
        Enemy,
        Friendly,
        All,
    }

    public enum SkillScanType {
        None,
        Target,
        Circle,
        Sector,
        Line,
        Donut,
    }

    public enum SkillDamageType {
        None,
        Physical,
        Magical,
        Pure,
    }

    public enum SkillEffectTypes {
        None,
        Damage,
        ActivateBuff,
        DeactivateBuff,
        IncreaseAttribute,
        DecreaseAttribute,
        ActivateAura,
    }

    public enum SkillAnchorType {
        None,
        Root,
        Center,
    }

    public enum StatTypes {
        None,
        ATK,
        ATK_Base,
        ATK_Add,
        ATK_Ratio,
        ATK_Amp,
        Pen_Physical,
        MATK,
        MATK_Base,
        MATK_Add,
        MATK_Ratio,
        MATK_Amp,
        Pen_Magic,
        CritRate,
        CritRate_Base,
        CritRate_Add,
        CritDam,
        CritDam_Base,
        CritDam_Add,
        CritDam_Ratio,
        SuperCritRate,
        SuperCritRate_Add,
        SuperCritDam,
        SuperCritDam_Add,
        SuperCritDam_Ratio,
        HP,
        HP_Base,
        HP_Add,
        HP_Ratio,
        HP_Amp,
        DEF,
        DEF_Base,
        DEF_Add,
        DEF_Ratio,
        MDEF,
        MDEF_Base,
        MDEF_Add,
        MDEF_Ratio,
        HP_Regen,
        HP_Regen_Base,
        HP_Regen_Add,
        HP_Regen_Ratio,
        LifeSteal_Ratio,
        DamReduce_Ratio,
        AtkSpeed,
        AtkSpeed_Base,
        AtkSpeed_Add,
        AtkSpeed_Ratio,
        MoveSpeed,
        MoveSpeed_Base,
        MoveSpeed_Ratio,
        Accuracy,
        Accuracy_Base,
        Accuracy_Add,
        BreakGage,
        BreakGage_Base,
        BreakGage_Add,
        BreakGage_Ratio,
        BreakGage_Amp,
        BreakDamage,
        BreakDamage_Base,
        BreakDamage_Add,
        BreakDamage_Ratio,
        BreakDamage_Amp,
        BreakRecovery,
        BreakRecovery_Base,
        BreakRecovery_Add,
        BreakRecovery_Ratio,
        BreakRecovery_Amp,
        Evasion,
        Evasion_Base,
        Evasion_Add,
        DamBoss_Ratio,
        DamNormal_Ratio,
        SkillDam_Ratio,
        NormalDam_Ratio,
        Cooldown_Reduce,
        GoldBonus_Ratio,
        ExpBonus_Ratio,
        ItemDrop_Ratio,
    }

    public enum UIZOrder {
        None,
        Background,
        Hud,
        View,
        Popup,
        Tooltip,
        Feedback,
        Notice,
        Loading,
        Fade,
        Interaction,
        DevConsole,
    }

    public enum UIEventIDs {
        None,
        Confirm,
        Cancel,
        Close,
        Select,
        Btn1,
        Btn2,
        Btn3,
        Btn4,
    }

    public enum SkillInfo {
        None,
        SKILL_BASEATTACK_01,
        SKILL_POWERATTACK_01,
        SKILL_PASSIVE_01,
        SKILL_PASSIVE_02,
        SKILL_MUSHROOM_ATTACK_01,
        SKILL_GOBLIN_ATTACK_01,
        SKILL_SKELETONWARRIOR_ATTACK_01,
        SKILL_SKELETONWARRIOR_ATTACK_02,
        SKILL_DEMON_ATTACK_01,
        SKILL_DEMON_ATTACK_02,
        SKILL_DEMON_ATTACK_03,
        SKILL_USE_POSTION_01,
        SKILL_USE_SCROLL_01,
        SKILL_BREAK_01,
    }

    public enum SkillEffect {
        None,
        SE_TAKE_DAMAGE_01,
        SE_TAKE_DAMAGE_02,
        SE_TAKE_DAMAGE_03,
        SE_TAKE_DAMAGE_04,
        SE_TAKE_DAMAGE_05,
        SE_TAKE_DAMAGE_06,
        SE_TAKE_DAMAGE_07,
        SE_TAKE_DAMAGE_08,
        SE_ACTIVATE_BUFF_MOVESPEED_01,
        SE_INCREASE_MOVESPEED_01,
        SE_ACTIVATE_BUFF_ATTACKSPEED_01,
        SE_INCREASE_ATTACKSPEED_01,
        SE_ACTIVATE_BUFF_POTION_01,
        SE_ACTIVATE_BUFF_SCROLL_01,
        SE_INCREASE_HP_01,
        SE_INCREASE_HP_INTERVAL_01,
        SE_ACTIVATE_DEBUFF_MOVESPEED_01,
        SE_DECREASE_MOVESPEED_01,
        SE_TAKE_DAMAGE_101,
        SE_ACTIVATE_BUFF_BREAK_01,
    }

    public enum BuffInfo {
        None,
        BUFF_MOVESPEED_01,
        BUFF_ATTACKSPEED_01,
        DEBUFF_MOVESPEED_01,
        BUFF_POTION_01,
        BUFF_DREAK_01,
        BUFF_STUN,
        BUFF_SILENCE,
        BUFF_BINDING,
    }

    public enum StatInfo {
        None,
        ATK,
        ATK_Base,
        ATK_Add,
        ATK_Ratio,
        ATK_Amp,
        Pen_Physical,
        MATK,
        MATK_Base,
        MATK_Add,
        MATK_Ratio,
        MATK_Amp,
        Pen_Magic,
        CritRate,
        CritRate_Base,
        CritRate_Add,
        CritDam,
        CritDam_Base,
        CritDam_Add,
        SuperCritRate,
        SuperCritRate_Base,
        SuperCritRate_Add,
        SuperCritDam,
        SuperCritDam_Base,
        SuperCritDam_Add,
        MaxHP,
        MaxHP_Base,
        MaxHP_Add,
        MaxHP_Ratio,
        MaxHP_Amp,
        DEF,
        DEF_Base,
        DEF_Add,
        DEF_Ratio,
        MDEF,
        MDEF_Base,
        MDEF_Add,
        MDEF_Ratio,
        HpRecovery,
        HpRecovery_Base,
        HpRecovery_Add,
        HpRecovery_Ratio,
        LifeSteal_Ratio,
        SpellVamp_Ratio,
        DamReduce_Ratio,
        AtkSpeed,
        AtkSpeed_Base,
        AtkSpeed_Add,
        AtkSpeed_Ratio,
        MoveSpeed,
        MoveSpeed_Base,
        MoveSpeed_Ratio,
        Accuracy,
        Accuracy_Base,
        Accuracy_Add,
        Accuracy_Ratio,
        BreakGage,
        BreakGage_Base,
        BreakGage_Add,
        BreakGage_Ratio,
        BreakGage_Amp,
        BreakDamage,
        BreakDamage_Base,
        BreakDamage_Add,
        BreakDamage_Ratio,
        BreakDamage_Amp,
        BreakRecovery,
        BreakRecovery_Base,
        BreakRecovery_Add,
        BreakRecovery_Ratio,
        BreakRecovery_Amp,
        Evasion,
        Evasion_Base,
        Evasion_Add,
        Block,
        Block_Base,
        Block_Add,
        DamBoss_Ratio,
        DamNormal_Ratio,
        SkillDam_Ratio,
        NormalDam_Ratio,
        Cooldown_Reduce,
        GoldBonus_Ratio,
        ExpBonus_Ratio,
        ItemDrop_Ratio,
    }

    public enum UIWidgetPath {
        None,
        IntroBG,
        IntroHUD,
        LegalNotice,
        LoginBG,
        LoginHUD,
        LoginServerList,
        LoginNotice,
        MainHUD,
        PlayerStats,
        SkillSlot,
        WorldMap,
        Inventory,
        ItemTooltip,
        SkillTree,
        SkillTooltip,
        DamageText,
        SystemNotice,
        LoadingScreen,
        FadeEffect,
        DragVisual,
        GameCursor,
        DevConsole,
    }

    public enum TableType {
        None,
        TableCharacter,
        TableConsumable,
        TableCurrencyInfo,
        TableEquipment,
        TableItemInfo,
        TableStageInfo,
        TableDungeonList,
        TableDungeonStage,
        TableMaterial,
        TableMonster,
        TableReward,
        TableSkillInfo,
        TableSkillEffect,
        TableBuffInfo,
        TableSkillSet,
        TableSkinInfo,
        TableStatInfo,
        TableBaseStat,
        TableUIWidgetPath,
    }

}
